language: cpp

compiler:  
  - gcc
  - clang

before_script:  
  - mkdir build
  - cd build
  - cmake ..

script: cmake --build .

addons:
    apt:
      packages:
       - cmake
      sources:
       - kalakris-cmake
